spring.application.name=EduPortal2
jwt.token.ttl=86400000
jwt.secretkey=EDUPORTALKEY

server.port=8080
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/eduportal
spring.datasource.username=postgres
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

supabase.url=https://dqijudqgouyibiiuuzpc.storage.supabase.co
supabase.api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxaWp1ZHFnb3V5aWJpaXV1enBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNDIzMzksImV4cCI6MjA5MDYxODMzOX0.7iR00QXhcAqilxEq9_Kg4PaSVYMbuX_g42NbAiJXjCM
supabase.bucket_name=media

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html`

server.tomcat.connection-timeout=3s

security.whitelist =/auth/**,/file/**,/swagger-ui/**,/swagger-ui.html,/v2/api-docs,/v3/api-docs,\
/v3/api-docs/swagger-config,/swagger-resources/**,/webjars/**,/ws/**,/index.html,/
gemini.api.key=AQ.Ab8RN6KAxlhNHuJGVbFyqqmcp4vjYQs8aNRqC_feycAzN1ogzQ

