spring.application.name=EduPortal2
jwt.token.ttl=86400000
jwt.secretkey=EDUPORTALKEY

gemini.api.key=AIzaSyCBiex1L-bWhA8gC4nLEvKdzWVZTAhkl64

server.port=8080
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/eduportal
spring.datasource.username=postgres
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true